### ISSUE TITLE
problem to install the lib

### ISSUE THREAD

**Issue by Elray02** [StanLepunK/ROMANESCO-Processing#2]
Hello I'm trying to use the lib with processing but is not recognize.
I have cloned the repo in my  /sketchbook/libraries/ closed and re open processing but nothing.
I have notice that other lib has a folder called "library", i have created one and i have put inside the .jar file but nothing change.
Any hint on what i can do?

My final goal is to arrive to run romanesco

I'm running processing 3.3.6 on a machine with linux mint with openjdk version "10.0.2" 2018-07-17

**Comment by knupel** [comment]
oups, i made my own library named Rope, and you can find this one no where except on my computer, my mistake. I just add a folder with special libraries and the list of the others. Update your clone and put the libraries from folder "external lib processing" in your library Processing folder. Plus I think is better your update your Processing 3.3.6 to 3.4.
